# Generated by Django 4.2.4 on 2023-09-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0002_remove_cryptocurrency_volume_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='percent_change',
            new_name='percent_change_24h',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='percent_change_1h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='percent_change_7d',
            field=models.DecimalField(decimal_places=8, default='0', max_digits=12),
            preserve_default=False,
        ),
    ]
